### ISSUE TITLE
Anlegen der Objekte unter 0_userdata.0 für Admin 5

### ISSUE THREAD

**Issue by dodi666** [dwm66/iobroker-scripts#3]
Hallo,
ist es vielleicht möglich, dass Skript für den Admin5 in soweit zu überarbeiten,
dass die Objekte unter 0_userdata.0 in einem eigenen Ordner angelegt werden?

Leider bekomme ich das selbst nicht für alle Objekte hin.

Grüße
Sascha

**Comment by dwm66** [comment]
Ich schau mir das mal an ...

**Comment by dodi666** [comment]
Super, vielen Dank schonmal!

**Comment by dodi666** [comment]
Hi, bist du schon dazu gekommen, dir das mal anzuschauen?

Grüße
Sascha

**Comment by ghost** [comment]
@dwm66
Vielen Dank für Deine Arbeit an den Scripten.
Ich fände es super, wenn es Datenpunkte für "Equalizer: bass, treble, loudness" gäbe,
evtl. auch noch für "previous Volume".

@dodi666 
Ich hatte auch schon versucht die Objekte in einem anderen Ordner anzulegen,
hat auch nicht zu 100% funktioniert.

**Comment by dodi666** [comment]
Ich habe es letzte Woche auch versucht, das Skript dahingehend abzuändern, dass die Datenpunkte im Bereich userdata angelegt werden. Das hat auch funktioniert, leider konnte ich dann aber die Player nicht mehr über das Skript steuern…
Somit bin ich dann wieder zum Original zurück….

**Comment by ghost** [comment]
Ich vermute das es nur im Objekt: "JavaScript" läuft, da sich hier auch die Scripte befinden.
btw. Hast Du zufällig die Datenpunkte "Equalizer: bass, treble, loudness" inkludieren können?
Hab das Script soweit geändert, das es mir die entsprechenden Datenpunkte im Ordner
"Equalizer" erstellt.
Leider werden diese bei Änderung noch nicht aktualisiert, ich arbeite daran.

Edit: Änderungen von "bass, treble..." werden jetzt angezeigt, leider nur wenn sich
andere "States" ändern und nicht wenn ich die Einstellungen über die Sonos-App
ändere. Das Ganze ist momentan auch nur "One-Way", also nur lesen der States.

**Comment by dodi666** [comment]
Nein, mit dem Thema habe ich mich nicht beschäftigt. Vielleicht können wir die beiden Themen mal im Forum platzieren. Gegebenenfalls können dort die JavaScript Profis ja helfen…

**Comment by dwm66** [comment]
0.11.1 sollte jetzt mit 0_userdata.0 funktionieren.

**Comment by dodi666** [comment]
> 0.11.1 sollte jetzt mit 0_userdata.0 funktionieren.

Bei mir funktioniert es soweit.
Vielen Dank

**Comment by dodi666** [comment]
Hi,
muss leider zurückrudern, funktioniert leider doch noch nicht.
Die Datenpunkte werden alle unter "0_userdata.0" angelegt.
Es kommt dann aber zu folgendem Fehler:
---------------------------------------------------------------------------------------------------------------------------
javascript.0 | 08:52:17.128 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.set":  Not found

javascript.0 | 08:52:17.129 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.say":  Not found

javascript.0 | 08:52:17.130 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.clip":  Not found

javascript.0 | 08:52:17.179 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI": Not  found

----------------------------------------------------------------------------------------------------------------------------

Für mich sieht es so aus, als wenn diese Datenpunkte nicht angelegt werden.
Danke für deine Hilfe

**Comment by dwm66** [comment]
Na ja ... gibts die Datenpunkte denn? In "Objects" mal angeschaut?
Bei welcher Operation tritt das denn auf?

In diesen Code läuft er nur rein, wenn auf der Sonos-API selbst ein Preset gelöscht wird. Benutzt Du Presets?

**Comment by dodi666** [comment]
Die Datenpunkte gibt es unter "objects" nicht.
"0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI." -> gibt es nicht!
"0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.example." -> den gibt es!
Was meinst du mit, bei welcher Operation tritt das auf?
Mir ist nicht bewusst, dass ich Presets benutze. Wenn ich ehrlich bin, weiß ich gerade garnicht, was das ist :-)
-> Habe das gerade nochmal nachgelesen...mir ist nicht bewusst, dass ich da was eingestellt habe...
Was bedeutet denn, "wenn auf der Sonos-API selbst ein Preset gelöscht wird"?
Die Meldungen habe ich nochmal unten angefügt...

`<html><body>

javascript.0 | 15:11:00.025 | info | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data: requestSonosAPI URL: http://192.168.1.37:5005/favorites
-- | -- | -- | --
javascript.0 | 15:11:13.010 | info | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data: requestSonosAPI URL: http://192.168.1.37:5005/playlists
javascript.0 | 15:11:17.015 | info | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data: requestSonosAPI URL: http://192.168.1.37:5005/preset
javascript.0 | 15:11:17.028 | info | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data: Preset SonosAPI not in presets any more
javascript.0 | 15:11:17.029 | info | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data: New presets are: ["example"]
javascript.0 | 15:11:17.130 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.set":  Not found
javascript.0 | 15:11:17.131 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.say":  Not found
javascript.0 | 15:11:17.132 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI.clip":  Not found
javascript.0 | 15:11:17.180 | error | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:  Cannot delete state  "0_userdata.0.javascript.PRG_011_SONOS.SonosAPI.Presets.SonosAPI": Not  found


</body>
</html>`

**Comment by dwm66** [comment]
Hm ... , das heißt, das System "glaubt", es gab mal einen Preset "SonosAPI", und den will es löschen, weil es nur mehr "example" gibt. Der "example" preset kommt vom Beispielfile in der SonosAPI, den solltest Du löschen ... das liegt in der SonosAPI selber, Unterverzeichnis "/presets", das file heißt example.json.

... Ok, das Problem lag in der Funktion getObjectsFromPreset(...), das nahm stur das 5. Element im Pfad... durch die Änderung kann der Pfad aber jetzt praktisch beliebig lang sein. Zäfix, saudämlicher Bug.

Fixed in 0.11.2

**Comment by dwm66** [comment]
> @dwm66 Vielen Dank für Deine Arbeit an den Scripten. Ich fände es super, wenn es Datenpunkte für "Equalizer: bass, treble, loudness" gäbe, evtl. auch noch für "previous Volume".
@pda1103 
DAS ist jetzt nicht so einfach. Im Prinzip kann man die Datenpunkte natürlich einbauen, die werden dann bei der regelmäßigen Abfrage des Status dann auch aufgefüllt.
Was NICHT funktioniert, ist eine sofortige Reaktion, wenn man den Equalizer z.B. mit der Sonos API ändert, weil der Callback/Webhook von der Sonos-API dann nicht aufgerufen wird. Das muss von der Sonos API selber kommen, da kann ich nix machen.

**Comment by dodi666** [comment]
> Hm ... , das heißt, das System "glaubt", es gab mal einen Preset "SonosAPI", und den will es löschen, weil es nur mehr "example" gibt. Der "example" preset kommt vom Beispielfile in der SonosAPI, den solltest Du löschen ... das liegt in der SonosAPI selber, Unterverzeichnis "/presets", das file heißt example.json.
> 
> ... Ok, das Problem lag in der Funktion getObjectsFromPreset(...), das nahm stur das 5. Element im Pfad... durch die Änderung kann der Pfad aber jetzt praktisch beliebig lang sein. Zäfix, saudämlicher Bug.
> 
> Fixed in 0.11.2

Okay, prima.
Vielen Dank, werde es morgen im Laufe des Tages mal ausprobieren.
Grüße

**Comment by dodi666** [comment]
@dwm66 Hi,
so dass Skript lässt sich jetzt erstmal fehlerfrei starten, leider gibt es bei der Bedienung der Datenpunkte (Play, Pause, etc.) eine Fehlermeldung:
`<html><body>

javascript.0 | 11:49:13.410 | warn | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:431:24)
-- | -- | -- | --
javascript.0 | 11:49:13.411 | warn | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)
javascript.0 | 11:49:13.414 | warn | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:432:25)
javascript.0 | 11:49:13.414 | warn | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)
javascript.0 | 11:49:13.417 | warn | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:433:27)
javascript.0 | 11:49:13.418 | warn | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)
javascript.0 | 11:49:13.422 | warn | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:434:24)
javascript.0 | 11:49:13.422 | warn | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)
javascript.0 | 11:49:13.426 | warn | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:435:22)
javascript.0 | 11:49:13.427 | warn | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)
javascript.0 | 11:49:13.436 | error | at canPlay (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:448:28)
javascript.0 | 11:49:13.437 | error | at Object.<anonymous> (script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data:535:15)


</body>
</html>`

Hoffe du kannst da was mit anfangen. Wenn ich noch was testen soll, bzw. du noch fragen hast, melde dich.

Grüße und Danke

**Comment by dodi666** [comment]
Erledigt mit Version 0.11.3

Vielen Dank
