### ISSUE TITLE
Script funktioniert mit Javascript Version 8.3.1 nicht mehr

### ISSUE THREAD

**Issue by dodi666** [dwm66/iobroker-scripts#4]
Offenbar funktioniert das Script mit der Version JS 8.3.1 nicht mehr.
Mit 7.8.0 war die Funktion noch gegeben.
https://forum.iobroker.net/topic/22888/sonos-http-api-installation-f%C3%BCr-newbies-dummies-und-mich/411?_=1716752249297

**Comment by dwm66** [comment]
Fixed, migrated to httpGet.

**Comment by dodi666** [comment]
> Fixed, migrated to httpGet.

Vielen Dank, funktioniert.
