### ISSUE TITLE
Skript Warnung: "More than 100 subscriptions registered"

### ISSUE THREAD

**Issue by dodi666** [dwm66/iobroker-scripts#5]
@dwm66 Hi,
kannst du dir das vielleicht auch nochmal ansehen?
`<html><body>

javascript.0 | 07:56:12.710 | warn | script.js.Eigene_Skripte.PRG_011_SONOS.Z_SonosAPI_Data_old: More than 100 subscriptions registered. Check your script!
-- | -- | -- | --

</body>
</html>`

Vielen Dank

**Comment by dwm66** [comment]
... stimmt ja auch.
Das Script generiert 20 subscriptions pro Raum, 7 Generell und dann noch paar für die Presets.
Man müsste die Warnung unterdrücken, sprich dem Javascript Adapter sagen "schon ok so". Keine Ahnung ob das geht.
